name: Behavioural Simulation

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      # Checkout repository
      - name: Checkout repo
        uses: actions/checkout@v5

      # Install icarus verilog simulator
      - name: Install iverilog
        shell: bash
        run: sudo apt-get update && sudo apt-get install -y iverilog

      # Set Python up and install cocotb
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Install required packages to run simulation
      - name: Install Python packages
        shell: bash
        run: pip install -r tb/bin/requirements.txt

      # Run simulation
      - name: Run tests
        run: |
          cd tb
          make clean
          make
          # make will return success even if the test fails, so check for failure in the results.xml
          ! grep failure results.xml

      # Collect results
      - name: Test Summary
        uses: test-summary/action@v2.3
        with:
          paths: "tb/results.xml"
        if: always()

      # Upload simulation wave dump
      - name: upload simulation dump
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-fst
          path: |
            tb/tb.fst
            tb/results.xml
