name: Behavioural Simulation Workflow with Verilator

on: [workflow_dispatch, workflow_call]

jobs:
  Run-Behavioural-Simulation-Verilator-Workflow:
    runs-on: ubuntu-24.04
    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v5

      # Get python packages
      - name: Install Python packages
        shell: bash
        run: pip install -r tb/bin/requirements.txt

      # Go to TB folder
      - name: Peprare for running simulation
        shell: bash
        run: |
          cd tb
          make clean

      # Install Verilator
      - name: Verilator version
        uses: fossi-foundation/verilator-action@v0.3
        with:
          version: latest
          arguments: '--version'

      # Run behavioral simulation with Verilator
      - name: Verilator Behavioural simulation
        uses: fossi-foundation/verilator-action@v0.3
        with:
          version: latest
          run: make SIM=verilator
        

      # Collect results
      - name: Test Summary
        if: always()
        uses: test-summary/action@v2.3
        with:
          paths: "tb/results.xml"

      # Upload simulation wave dump
      - name: Upload Waveform and Test Results
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: behavioural_test_results_verilator
          path: |
            tb/tb.vcd
            tb/tb.fst
            tb/results.xml
