name: Behavioural Simulation Workflow with Verilator

on: [workflow_dispatch, workflow_call]

jobs:
  Run-Behavioural-Simulation-Verilator-Workflow:
    runs-on: ubuntu-24.04
    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v5

      # Get python packages
      - name: Install Python packages
        shell: bash
        run: pip install -r tb/bin/requirements.txt

      # Install Verilator
      - name: Install verilator
        shell: bash
        run: run: |
          wget https://launchpad.net/ubuntu/+source/verilator/5.032-1/+build/29941374/+files/verilator_5.032-1_amd64.deb
          sudo apt-get update -y
          sudo apt-get install -y ./verilator_5.032-1_amd64.deb

      # Run simulation
      - name: Run tests
        run: |
          cd tb
          make clean
          make SIM=verilator
          # make will return success even if the test fails, so check for failure in the results.xml
          ! grep failure results.xml

      # Collect results
      - name: Test Summary
        if: always()
        uses: test-summary/action@v2.3
        with:
          paths: "tb/results.xml"

      # Upload simulation wave dump
      - name: Upload Waveform and Test Results
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: behavioural_test_results_verilator
          path: |
            tb/tb.vcd
            tb/tb.fst
            tb/results.xml
