name: Behavioural Simulation Workflow with iverilog

on: [workflow_dispatch, workflow_call]

jobs:
  Run-Behavioural-Simulation-Iverilog-Workflow:
    runs-on: ubuntu-24.04
    steps:
      # Checkout repository
      - name: Checkout repo
        uses: actions/checkout@v5

      # Set Python up
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Install required packages
      - name: Install Python packages
        shell: bash
        run: pip install -r tb/bin/requirements.txt

      # Install icarus verilog simulator
      - name: Install iverilog
        shell: bash
        run: sudo apt-get update && sudo apt-get install -y iverilog

      # Run simulation
      - name: Run tests
        run: |
          cd tb
          make clean
          make
          # make will return success even if the test fails, so check for failure in the results.xml
          ! grep failure results.xml

      # Collect results
      - name: Test Summary
        if: always()
        uses: test-summary/action@v2.4
        with:
          paths: "tb/results.xml"

      # Upload simulation wave dump
      - name: Upload Waveform and Test Results
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: behavioural_test_results_iverilog
          path: |
            tb/tb.vcd
            tb/tb.fst
            tb/results.xml
