name: GDS Workflow

on: [push, workflow_dispatch]

jobs:

  #Run-Verilator-Lint-Workflow:
  #  uses: ./.github/workflows/verilator-lint.yml

  Run-GDS-Workflow:
    uses: ./.github/workflows/librelane-action.yml

  Run-Gate-Level-Workflow:
    needs: Run-GDS-Workflow
    uses: ./.github/workflows/gl-sim-action.yml