name: Gate Level Simulation Workflow

on: [workflow_dispatch, workflow_call]

#inputs:
#  test-dir:
#    description: 'The directory with the Makefile for running the tests'
#    required: true
#    default: 'test'

jobs:
  Run-Gate-Level-Simuation-Workflow:
    runs-on: ubuntu-24.04
    steps:

      # Download gate level netlist
      - name: Download GDS artifact
        uses: actions/download-artifact@v5
        with:
          name: librelane-logs

    #  - name: Set up environment variables
    #    working-directory: tt_submission
    #    shell: bash
    #    run: |
    #      # Defaults
    #      PDK=$(jq -r '.PDK' pdk.json)
    #      PDK_ROOT=/home/runner/pdk
    #      PDK_SOURCE=$(jq -r '.PDK_SOURCE' pdk.json)
    #      PDK_VERSION=$(jq -r '.PDK_VERSION' pdk.json)

    #      cat << __EOF >> $GITHUB_ENV
    #      PDK=$PDK
    #      PDK_ROOT=$PDK_ROOT
    #      PDK_SOURCE=$PDK_SOURCE
    #      PDK_VERSION=$PDK_VERSION
    #      __EOF

      - name: Install PDK
        uses: TinyTapeout/ciel-action@v1
        with:
          pdk_name: ihp-sg13g2
          pdk_version: cb7daaa8901016cf7c5d272dfa322c41f024931f
          pdk_root: /home/runner/pdk

      # Install icarus verilog simulator
      - name: Install iverilog
        shell: bash
        run: sudo apt-get update && sudo apt-get install -y iverilog

      # Set Python up
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Checkout repository
      - name: Checkout repo
        uses: actions/checkout@v5

      # Install required packages
      - name: Install Python packages
        shell: bash
        run: pip install -r tb/bin/requirements.txt

      # Run simulation
      - name: Run Gate Level Simulation tests
        shell: bash
        run: |
          cd tb
          rm -f tb.vcd tb.fst results.xml
          make clean

          # `make` will return success even if the tests fail, so check for failure in results.xml
          test -f results.xml
          ! grep failure results.xml

      - name: Upload Waveform and Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
            name: gatelevel_test_results
            path: |
              tb/tb.vcd
              tb/tb.fst
              tb/results.xml
              tb/output/*

      - name: Test Summary
        if: always()
        uses: test-summary/action@v2.3
        with:
          paths: tb/results.xml