name: Gate Level Simulation Workflow

on: [workflow_dispatch, workflow_call]

jobs:
  Run-Gate-Level-Simuation-Workflow:
    runs-on: ubuntu-24.04
    steps:

      # Download Librelane artifact
      - name: Download GDS artifact
        uses: actions/download-artifact@v5
        with:
          name: librelane-logs

      # Install PDK
      - name: Install PDK
        uses: TinyTapeout/ciel-action@v1
        with:
          pdk_name: ihp-sg13g2
          pdk_version: cb7daaa8901016cf7c5d272dfa322c41f024931f
          pdk_root: /home/runner/pdk

      # Install icarus verilog simulator
      - name: Install iverilog
        shell: bash
        run: sudo apt-get update && sudo apt-get install -y iverilog

      # Set Python up
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Checkout repository
      - name: Checkout repo
        uses: actions/checkout@v5

      # Install required packages
      - name: Install Python packages
        shell: bash
        run: pip install -r tb/bin/requirements.txt
      
      # Copy gate level netlist
      - name : Copy Gate Leve netlist from artifact
        shell: bash
        run: |
          find . \
          -path "*/final/nl/i2c_slave.nl.v" \
          -type f \
          -exec cp {} tb/gate_level_netlist.v \;

      # Run simulation
      - name: Run Gate Level Simulation tests
        shell: bash
        run: |
          cd tb
          tree
          rm -f tb.vcd tb.fst results.xml
          make clean
          make GATES=yes
          # `make` will return success even if the tests fail, so check for failure in results.xml
          ! grep failure results.xml

      - name: Test Summary
        if: always()
        uses: test-summary/action@v2.3
        with:
          paths: tb/results.xml

      - name: Upload Waveform and Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
            name: gatelevel_test_results
            path: |
              tb/tb.vcd
              tb/tb.fst
              tb/results.xml