name: Gate Level Simulation Workflow

on: [push, workflow_dispatch]

#inputs:
#  test-dir:
#    description: 'The directory with the Makefile for running the tests'
#    required: true
#    default: 'test'

jobs:
  Run-Gate-Level-Simuation-Workflow:
    runs-on: ubuntu-24.04
    #using: 'composite'
    steps:

      # Checkout repository
      - name: Checkout repo
        uses: actions/checkout@v5

    #  - name: Download GDS artifact
    #    uses: actions/download-artifact@v4
    #    with:
    #      name: tt_submission

    #  - name: Set up environment variables
    #    working-directory: tt_submission
    #    shell: bash
    #    run: |
    #      # Defaults
    #      PDK=$(jq -r '.PDK' pdk.json)
    #      PDK_ROOT=/home/runner/pdk
    #      PDK_SOURCE=$(jq -r '.PDK_SOURCE' pdk.json)
    #      PDK_VERSION=$(jq -r '.PDK_VERSION' pdk.json)

    #      cat << __EOF >> $GITHUB_ENV
    #      PDK=$PDK
    #      PDK_ROOT=$PDK_ROOT
    #      PDK_SOURCE=$PDK_SOURCE
    #      PDK_VERSION=$PDK_VERSION
    #      __EOF

      - name: Install PDK
        uses: TinyTapeout/ciel-action@v1
        with:
          pdk_name: ihp-sg13g2
          pdk_version: cb7daaa8901016cf7c5d272dfa322c41f024931f
          pdk_root: /home/runner/pdk

      # Set Python up
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Install required packages
      - name: Install Python packages
        shell: bash
        run: pip install -r tb/bin/requirements.txt

      # Install icarus verilog simulator
      - name: Install iverilog
        shell: bash
        run: sudo apt-get update && sudo apt-get install -y iverilog

      # Run simulation
      #- name: Run tests
      #  shell: bash
      #  run: |
      #    cp tt_submission/*.v "${{ inputs.test-dir }}/gate_level_netlist.v"
      #    cd "${{ inputs.test-dir }}"
      #    rm -f tb.vcd tb.fst results.xml
      #    make clean
      #    GATES=yes make

      #    # `make` will return success even if the tests fail, so check for failure in results.xml
      #    test -f results.xml
      #    ! grep failure results.xml

      #- name: Upload Waveform and Test Results
      #  if: always()
      #  uses: actions/upload-artifact@v4
      #  with:
      #      name: gatelevel_test_results
      #      path: |
      #        ${{ inputs.test-dir }}/tb.vcd
      #        ${{ inputs.test-dir }}/tb.fst
      #        ${{ inputs.test-dir }}/results.xml
      #        ${{ inputs.test-dir }}/output/*

      #- name: Test Summary
      #  if: always()
      #  uses: test-summary/action@v2.3
      #  with:
      #    paths: ${{ inputs.test-dir }}/results.xml