name: Verilator Lint

on: push

jobs:
  Run-Verilator-Lint-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      
      - name: Verilator version
        uses: fossi-foundation/verilator-action@v0.3
        with:
          version: latest
          arguments: '--version'

      - name: Verilator Linting
        uses: fossi-foundation/verilator-action@v0.3
        with:
          version: latest
          working-directory: 'src'
          lint-files: 'src/i2c_slave.v'
